# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "333333333333333330e"
application_url = "https://bottle-drag-surveillance-tuition.trycloudflare.com"
embedded = true
name = "late-night-remix"
handle = "late-night-remix"

[build]
include_config_on_deploy = true
automatically_update_urls_on_dev = true

[webhooks]
api_version = "2025-01"

[[webhooks.subscriptions]]
topics = ["app/uninstalled"]
uri = "/webhooks/app/uninstalled"

[[webhooks.subscriptions]]
topics = ["app/scopes_update"]
uri = "/webhooks/app/scopes_update"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_products,write_orders,read_customers,write_draft_orders"

[auth]
redirect_urls = [
  "https://bottle-drag-surveillance-tuition.trycloudflare.com/auth/callback",
  "https://bottle-drag-surveillance-tuition.trycloudflare.com/auth/shopify/callback",
  "https://bottle-drag-surveillance-tuition.trycloudflare.com/api/auth/callback",
]

[pos]
embedded = false
